[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "^1.0.4"
